language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install python-lxml
install:
  - pip install -r dev_requirements.txt
script:
  - coverage run setup.py test
  - flake8 .
after_success:
  coveralls
notifications:
  email:
    - ci-notify@openlabs.co.in
